# More ideas:
# https://github.com/adelsz/pgtyped/blob/master/packages/example/docker-compose.yml

version: "3.9"

services:
  db:
    image: postgres:14.6-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=${PGHOST}
      - POSTGRES_PORT=${PGPORT}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d/

volumes:
  db:
