# More ideas:
# https://github.com/adelsz/pgtyped/blob/master/packages/example/docker-compose.yml

version: "3.9"

# Set so-called "project" name here for "postgresql_volume" as volume name
name: "postgresql"

services:
  postgresql:
    container_name: postgresql_container
    image: postgres:14.6-alpine
    restart: unless-stopped
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_DB=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    ports:
      - ${POSTGRESQL_PORT}:${POSTGRESQL_PORT}
    volumes:
      - volume:/var/lib/postgresql/data
      - ./models/schema/:/docker-entrypoint-initdb.d/

volumes:
  volume:

networks:
  default:
    name: postgresql_network