version: "3.9"

name: ${DOCKER_PROJECT}

services:
  webpack:
    image: webpack:latest
    container_name: ${WEBPACK_DOCKER_CONTAINER}
    hostname: ${WEBPACK_DOCKER_CONTAINER}
    build:
      context: ./webpack
      args:
        PROJECT_OWNER: ${PROJECT_OWNER}
        PROJECT_EMAIL: ${PROJECT_EMAIL}
        WEBPACK_DEV_SERVER_PORT: ${WEBPACK_DEV_SERVER_PORT}
    volumes:
      - external-volume:/app
      - type: bind
        source: ../projects/typescript-example
        target: /app/project
    ports:
      - ${WEBPACK_DEV_SERVER_PORT}:${WEBPACK_DEV_SERVER_PORT}

volumes:
  external-volume:
    name: ${WEBPACK_DOCKER_VOLUME}

networks:
  default:
    name: ${DOCKER_NETWORK_PUBLIC}
    external: true
