version: "3.9"

name: ${DOCKER_PROJECT}

services:
  mongo:
    image: mongo:6-jammy
    container_name: ${MONGODB_DOCKER_CONTAINER}
    hostname: ${MONGODB_DOCKER_CONTAINER}
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb://mongodb:${MONGODB_PORT}/${MONGODB_DATABASE}
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - external-volume:/data/db

volumes:
  external-volume:
    name: ${MONGODB_DOCKER_VOLUME}

networks:
  default:
    name: ${DOCKER_NETWORK_PUBLIC}
    external: true
